services:
  php:
    container_name: php
    build: php
    volumes:
      - ./src:/var/www/html
    networks:
      - backend

  apache:
    container_name: apache
    build: apache
    volumes:
      - ./src:/var/www/html
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80:80"
    networks:
      - backend

  pgsql:
    container_name: pgsql
    build: pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data:

networks:
  backend:
    driver: bridge