services:
  php:
    container_name: php
    build: php
    volumes:
      - ./src:/var/www/html
    networks:
      - apacheAndPhp

  apache:
    container_name: apache
    build: apache
    volumes:
      - ./src:/var/www/html
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80:80"
    networks:
      - apacheAndPhp

networks:
  apacheAndPhp:
    driver: bridge